# Generated by Django 2.1.5 on 2019-01-31 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repository.filesystems


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file_hash', models.CharField(max_length=40)),
                ('file', models.FileField(blank=True, null=True, storage=repository.filesystems.ManagedFileSystemStorage(), upload_to=repository.filesystems.upload_dynamic_path)),
                ('dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ManagedFile')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('root_folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_repository', related_query_name='root_repository', to='repository.ManagedFile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ManagedFile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'owner')},
        ),
    ]
