# Generated by Django 2.1.5 on 2019-01-30 07:17

from django.db import migrations, models
import django.db.models.deletion
import repository.filesystems


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file',
            field=models.FileField(storage=repository.filesystems.ManagedFileSystemStorage(), upload_to=repository.filesystems.upload_dynamic_path),
        ),
        migrations.AddField(
            model_name='trackedfileinfo',
            name='managed_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ManagedFile'),
        ),
    ]
